---
nwmaster-server:
  host: set.your.listen.ip.here
  port: 5121

gamespy-server:
  host: set.your.listen.ip.here
  port: 27900

game-version: "8109"

# Pass authentication data through to
# the original servers.
mode: passthru

# SQL-based authentication.
# Set up empty database by running:
#   sqlite3 nwmaster.db < mode_sql.sql
mode: sql

# Always allow authentication.
mode: dummy
...
